name: Build and Upload ECR image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted, linux, high-memory]  # Specify labels to target specific runners
    steps:
      - uses: actions/checkout@v3

      - name: Set AWS Region Environment Variable
        run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Add user to docker group
        run: sudo usermod -aG docker $(whoami)

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin 871548798187.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: travel_guide
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/travel-guide-deployment travel-guide-container=$REGISTRY/$REPOSITORY:$IMAGE_TAG -n default