name: Build and Upload ECR image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted, linux, high-memory]  # Specify labels to target specific runners
    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: travel_guide
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/travel-guide-deployment travel-guide-container=$REGISTRY/$REPOSITORY:$IMAGE_TAG -n default