name: Build and Upload ECR image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted, ubuntu]  # Specify labels to target specific runners
    steps:
      - uses: actions/checkout@v3

      - name: Set AWS Region Environment Variable
        run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Add user to docker group
        run: sudo usermod -aG docker $(whoami)

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin 871548798187.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          echo "REGISTRY=871548798187.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: travel_guide
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sudo docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          sudo docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV

      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          repository: ceztro/ArgoCD_GitOps
          ref: dev
          path: git_ops
          token: ${{ secrets.GIT_OPS_REPO_TOKEN }}
          persist-credentials: true

      - name: Update image tag in values.yaml
        run: |
          sed -i "s/tag:.*/tag: ${{ env.IMAGE_TAG }}/" git_ops/travel_guide/values.yaml

      - name: Commit and Push Changes to GitOps Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_OPS_REPO_TOKEN }}
        run: |
          cd git_ops
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add travel_guide/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push origin dev